"""ORCA alert engine — threshold-driven, REAL conditions only.

Two alert streams:

  1. LIVE alerts — generated by evaluating actual data for a point:
       waves / wind gusts / rain from the point forecast, plus active
       JTWC cyclones. Nothing is invented; thresholds are official
       small-craft / WMO / IMD numbers.
  2. SIMULATED alerts — for demo & disaster-drill only, created via
     POST /api/v1/alerts/simulate. ALWAYS carry simulated=true and a
     🧪 DEMO prefix so nobody can mistake them for a real warning.

Alerts live in an in-process store with a validity window; WebSocket
clients get them pushed as `alert.push` events.
"""
from __future__ import annotations

import asyncio
import itertools
from datetime import datetime, timedelta, timezone
from typing import Any

from pipeline import forecast as fc
from pipeline import jtwc

_alert_seq = itertools.count(1)
_store: list[dict[str, Any]] = []
_subscribers: set[asyncio.Queue] = set()


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _mk_alert(
    code: str,
    severity: str,  # "watch" | "warning"
    title_en: str,
    title_hi: str,
    msg_en: str,
    lat: float,
    lon: float,
    valid_hours: float,
    source: str,
    simulated: bool = False,
    extra: dict[str, Any] | None = None,
) -> dict[str, Any]:
    issued = _now()
    a = {
        "id": f"alert-{next(_alert_seq):05d}",
        "code": code,
        "severity": severity,
        "simulated": simulated,
        "title_en": ("🧪 DEMO: " if simulated else "") + title_en,
        "title_hi": ("🧪 DEMO: " if simulated else "") + title_hi,
        "msg_en": msg_en,
        "lat": lat,
        "lon": lon,
        "issued_at": issued.isoformat(timespec="seconds"),
        "valid_until": (issued + timedelta(hours=valid_hours)).isoformat(timespec="seconds"),
        "source": source,
    }
    if extra:
        a.update(extra)
    return a


# ── Live evaluation ────────────────────────────────────────────────

def evaluate(lat: float, lon: float) -> list[dict[str, Any]]:
    """Check REAL conditions at this point and mint alerts for anything
    that crosses a threshold. Returns [] when everything is calm — that
    is itself a true statement, not a placeholder."""
    new_alerts: list[dict[str, Any]] = []

    # -- Sea state + weather (next 24 h) --
    try:
        point_fc = fc.get_point_forecast(lat, lon)
        n24 = point_fc.get("next24h", {})
        src = point_fc.get("source", "Open-Meteo")

        w = n24.get("wave_max_m")
        if w is not None:
            if w >= 3.5:
                new_alerts.append(_mk_alert(
                    "high_waves", "warning",
                    f"High waves: up to {w:.1f} m in next 24 h",
                    f"ऊँची लहरें: अगले 24 घंटे में {w:.1f} मीटर तक",
                    f"Wave heights up to {w:.1f} m expected within 24 h near "
                    f"({lat:.2f}, {lon:.2f}). Small craft should not venture out.",
                    lat, lon, 24, src))
            elif w >= 2.5:
                new_alerts.append(_mk_alert(
                    "waves_elevated", "watch",
                    f"Rough seas: waves up to {w:.1f} m",
                    f"खराब समुद्र: लहरें {w:.1f} मीटर तक",
                    f"Waves up to {w:.1f} m expected in 24 h — caution for small boats.",
                    lat, lon, 24, src))

        g = n24.get("gust_max_kn")
        if g is not None:
            if g >= 34:
                new_alerts.append(_mk_alert(
                    "gale", "warning",
                    f"Gale warning: gusts up to {g:.0f} kn",
                    f"तेज़ हवा चेतावनी: झौंके {g:.0f} नॉट तक",
                    f"Gale-force gusts up to {g:.0f} kn forecast in 24 h "
                    "(WMO gale = ≥ 34 kn). Stay in harbour.",
                    lat, lon, 24, src))
            elif g >= 28:
                new_alerts.append(_mk_alert(
                    "wind_strong", "watch",
                    f"Strong winds: gusts up to {g:.0f} kn",
                    f"तेज़ हवा: झौंके {g:.0f} नॉट तक",
                    f"Gusts up to {g:.0f} kn in next 24 h — secure gear, plan accordingly.",
                    lat, lon, 24, src))

        rain = n24.get("rain_total_mm")
        if rain is not None and rain >= 64.5:
            new_alerts.append(_mk_alert(
                "heavy_rain", "warning",
                f"Heavy rain: ~{rain:.0f} mm in 24 h",
                f"भारी बारिश: 24 घंटे में ~{rain:.0f} मिमी",
                f"~{rain:.0f} mm rain in 24 h crosses the IMD heavy-rain threshold "
                "(≥ 64.5 mm). Poor visibility at sea.",
                lat, lon, 24, src))
    except Exception:  # noqa: BLE001
        pass  # forecast unreachable → we simply issue no weather alerts (honest)

    # -- Tropical cyclones (JTWC) --
    try:
        # Basin-filtered: ORCA serves Indian waters, so a Northwest
        # Pacific typhoon must never mint an alert here. "io" = North
        # Indian Ocean; "sh" = South Indian/Pacific (relevant south of
        # the equator); distance gates below still apply.
        cyc = jtwc.nearest_cyclone(lat, lon, basins=["io", "sh"])
        if cyc.get("found"):
            c = cyc["cyclone"]
            d = cyc["distance_km"]
            nm = round(d / 1.852)
            label = c.get("name") or c["designation"]
            if d < 500:
                sev, hrs = "warning", 12
            elif d < 1000:
                sev, hrs = "watch", 24
            else:
                sev = hrs = None
            if sev:
                new_alerts.append(_mk_alert(
                    "tropical_cyclone", sev,
                    f"Cyclone {label}: {nm} NM away",
                    f"चक्रवात {label}: {nm} NM दूर",
                    f"{c.get('intensity', 'Tropical system')} '{label}' is {nm} NM away "
                    f"with max winds {c.get('max_wind_kt', '?')} kn "
                    f"(JTWC advisory #{c.get('advisory_no', '?')}). Monitor bulletins.",
                    lat, lon, hrs, c.get("source", "JTWC"),
                    extra={"cyclone": c, "distance_km": d}))
    except Exception:  # noqa: BLE001
        pass

    _store.extend(new_alerts)
    _prune()
    return new_alerts


# ── Simulation (demo lever — honestly labelled) ────────────────────

def simulate(kind: str, lat: float, lon: float) -> dict[str, Any]:
    """Create a clearly-labelled simulated alert for demos/drills.
    kind: only 'cyclone' for now (the blueprint's golden flow C)."""
    if kind != "cyclone":
        raise ValueError(f"unknown simulation kind: {kind!r}")
    a = _mk_alert(
        "tropical_cyclone", "warning",
        "Simulated cyclone approaching coast",
        "सिम्युलेटेड चक्रवात तट की ओर",
        "SIMULATED alert for demonstration: a cyclone ~180 NM offshore, "
        "moving toward the coast at 12 kn. In production this card is "
        "generated from real JTWC advisories only.",
        lat, lon, 6, "ORCA demo mode",
        simulated=True,
        extra={"cyclone": {
            "name": "DEMOZERO", "lat": lat - 1.5, "lon": lon - 2.5,
            "max_wind_kt": 55, "intensity": "Severe Cyclonic Storm (simulated)",
            "movement_deg": 45, "movement_kt": 12, "simulated": True,
        }, "distance_km": 333},
    )
    _store.append(a)
    _prune()
    return a


# ── Store, subscription, cleanup ───────────────────────────────────

def _prune() -> None:
    now_iso = _now().isoformat(timespec="seconds")
    _store[:] = [a for a in _store if a["valid_until"] > now_iso]
    del _store[:-100]  # cap memory


def list_alerts(since: str | None = None) -> list[dict[str, Any]]:
    _prune()
    if since:
        return [a for a in _store if a["issued_at"] > since]
    return list(_store)


def subscribe() -> asyncio.Queue:
    q: asyncio.Queue = asyncio.Queue(maxsize=50)
    _subscribers.add(q)
    return q


def unsubscribe(q: asyncio.Queue) -> None:
    _subscribers.discard(q)


async def publish(alert: dict[str, Any]) -> None:
    """Push one alert to every connected WebSocket client."""
    for q in list(_subscribers):
        try:
            q.put_nowait({"type": "alert.push", "alert": alert})
        except asyncio.QueueFull:
            pass
